version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/${{ github.event.repository.name }}"
    - "src/Tests/${{ github.event.repository.name }}.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
